-- Round 7: Load structured synthetic CSV datasets from the internal stage.

USE ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
USE WAREHOUSE MEDICAL_AFFAIRS_DEMO_WH;
USE DATABASE MEDICAL_AFFAIRS_AI;
USE SCHEMA MEDICAL_AFFAIRS;

TRUNCATE TABLE THERAPEUTIC_AREA;
TRUNCATE TABLE PRODUCT;
TRUNCATE TABLE INDICATION;
TRUNCATE TABLE STUDY;
TRUNCATE TABLE TREATMENT_ARM;
TRUNCATE TABLE PATIENT_POPULATION;
TRUNCATE TABLE EFFICACY_ENDPOINT;
TRUNCATE TABLE SAFETY_EVENT;

COPY INTO THERAPEUTIC_AREA
  FROM @STRUCTURED_DATA_STAGE/therapeutic_area.csv
  FILE_FORMAT = (FORMAT_NAME = MEDICAL_AFFAIRS_CSV_FF)
  FORCE = TRUE;

COPY INTO PRODUCT
  FROM @STRUCTURED_DATA_STAGE/product.csv
  FILE_FORMAT = (FORMAT_NAME = MEDICAL_AFFAIRS_CSV_FF)
  FORCE = TRUE;

COPY INTO INDICATION
  FROM @STRUCTURED_DATA_STAGE/indication.csv
  FILE_FORMAT = (FORMAT_NAME = MEDICAL_AFFAIRS_CSV_FF)
  FORCE = TRUE;

COPY INTO STUDY
  FROM @STRUCTURED_DATA_STAGE/study.csv
  FILE_FORMAT = (FORMAT_NAME = MEDICAL_AFFAIRS_CSV_FF)
  FORCE = TRUE;

COPY INTO TREATMENT_ARM
  FROM @STRUCTURED_DATA_STAGE/treatment_arm.csv
  FILE_FORMAT = (FORMAT_NAME = MEDICAL_AFFAIRS_CSV_FF)
  FORCE = TRUE;

COPY INTO PATIENT_POPULATION
  FROM @STRUCTURED_DATA_STAGE/patient_population.csv
  FILE_FORMAT = (FORMAT_NAME = MEDICAL_AFFAIRS_CSV_FF)
  FORCE = TRUE;

COPY INTO EFFICACY_ENDPOINT
  FROM @STRUCTURED_DATA_STAGE/efficacy_endpoint.csv
  FILE_FORMAT = (FORMAT_NAME = MEDICAL_AFFAIRS_CSV_FF)
  FORCE = TRUE;

COPY INTO SAFETY_EVENT
  FROM @STRUCTURED_DATA_STAGE/safety_event.csv
  FILE_FORMAT = (FORMAT_NAME = MEDICAL_AFFAIRS_CSV_FF)
  FORCE = TRUE;
