-- Round 7: Load document manifest, citation index, and approved medical response metadata.

USE ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
USE WAREHOUSE MEDICAL_AFFAIRS_DEMO_WH;
USE DATABASE MEDICAL_AFFAIRS_AI;
USE SCHEMA MEDICAL_AFFAIRS;

TRUNCATE TABLE SCIENTIFIC_DOCUMENT_MANIFEST;
TRUNCATE TABLE DOCUMENT_CITATION;
TRUNCATE TABLE APPROVED_MEDICAL_RESPONSE;

COPY INTO SCIENTIFIC_DOCUMENT_MANIFEST
  FROM @METADATA_STAGE/document_manifest.csv
  FILE_FORMAT = (FORMAT_NAME = MEDICAL_AFFAIRS_CSV_FF)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FORCE = TRUE;

COPY INTO DOCUMENT_CITATION
  FROM @METADATA_STAGE/document_citation.csv
  FILE_FORMAT = (FORMAT_NAME = MEDICAL_AFFAIRS_CSV_FF)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FORCE = TRUE;

COPY INTO APPROVED_MEDICAL_RESPONSE
  FROM @METADATA_STAGE/approved_medical_response.csv
  FILE_FORMAT = (FORMAT_NAME = MEDICAL_AFFAIRS_CSV_FF)
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  FORCE = TRUE;
