-- Round 5 — Snowflake Bootstrap
-- Grants least-privilege access required for current bootstrap and later dedicated build rounds.
-- Run with SECURITYADMIN (or a role with MANAGE GRANTS).

USE ROLE SECURITYADMIN;

-- Container and compute usage.
GRANT USAGE ON WAREHOUSE MEDICAL_AFFAIRS_DEMO_WH TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT USAGE ON DATABASE MEDICAL_AFFAIRS_AI TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT USAGE ON SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;

-- Existing bootstrap objects.
GRANT USAGE ON FILE FORMAT MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.MEDICAL_AFFAIRS_CSV_FF TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT USAGE ON FILE FORMAT MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.MEDICAL_AFFAIRS_JSON_FF TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT READ, WRITE ON STAGE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.STRUCTURED_DATA_STAGE TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT READ, WRITE ON STAGE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.SCIENTIFIC_DOCUMENT_STAGE TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT READ, WRITE ON STAGE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.METADATA_STAGE TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;

-- Creation privileges for later rounds. These grants DO NOT create the objects.
GRANT CREATE TABLE ON SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT CREATE VIEW ON SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT CREATE STAGE ON SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT CREATE SEMANTIC VIEW ON SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT CREATE AGENT ON SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;

-- Future table/view access ensures objects produced by later data-loading rounds remain usable
-- by the demo role even when created by an administrative deployment role.
GRANT SELECT ON FUTURE TABLES IN SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;

-- Cortex feature database roles are intentionally NOT granted in Round 5.
-- Round 9/10 will grant the minimum required SNOWFLAKE.CORTEX_* database roles after
-- the exact Search/Agent implementation has been validated against the target account.
