-- Round 9: Cortex Search privileges
-- Grants the minimal Snowflake-managed Cortex role needed to create/use managed embeddings
-- plus explicit object privileges for the Medical Affairs demo role.

USE ROLE ACCOUNTADMIN;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_EMBED_USER
  TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;

GRANT CREATE CORTEX SEARCH SERVICE
  ON SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS
  TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;

GRANT USAGE
  ON WAREHOUSE MEDICAL_AFFAIRS_DEMO_WH
  TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;

GRANT SELECT
  ON TABLE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.SCIENTIFIC_DOCUMENT
  TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
