-- Round 10: Cortex Agent privileges
-- Grants the narrow Cortex Agent database role and object privileges needed to create/use the demo agent.

USE ROLE ACCOUNTADMIN;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_AGENT_USER TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;

GRANT CREATE AGENT ON SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS
  TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;

GRANT USAGE ON DATABASE MEDICAL_AFFAIRS_AI
  TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT USAGE ON SCHEMA MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS
  TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT USAGE ON WAREHOUSE MEDICAL_AFFAIRS_DEMO_WH
  TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;

GRANT USAGE ON CORTEX SEARCH SERVICE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.MEDICAL_SCIENTIFIC_SEARCH
  TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT USAGE ON SEMANTIC VIEW MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.CLINICAL_EVIDENCE_SEMANTIC_VIEW
  TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;

-- Underlying structured objects referenced by the semantic view.
GRANT SELECT ON TABLE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.STUDY TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT SELECT ON TABLE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.PRODUCT TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT SELECT ON TABLE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.INDICATION TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT SELECT ON TABLE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.TREATMENT_ARM TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT SELECT ON TABLE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.PATIENT_POPULATION TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT SELECT ON TABLE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.EFFICACY_ENDPOINT TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
GRANT SELECT ON TABLE MEDICAL_AFFAIRS_AI.MEDICAL_AFFAIRS.SAFETY_EVENT TO ROLE MEDICAL_AFFAIRS_DEMO_ROLE;
